services:
  mysql:
    image: mysql:8.0
    container_name: credit-card-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: credit_card_payment_db
      MYSQL_ROOT_PASSWORD: change_this_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    image: credit-card-django:latest
    container_name: credit-card-django
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: credit_card_payment_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: change_this_password
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
    ports:
      - "8000:8000"

  fastapi:
    image: credit-card-fastapi:latest
    container_name: credit-card-fastapi
    restart: unless-stopped
    depends_on:
      - mysql
      - django
    environment:
      MYSQL_DATABASE: credit_card_payment_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: change_this_password
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: credit-card-frontend:latest
    container_name: credit-card-frontend
    restart: unless-stopped
    depends_on:
      - django
      - fastapi
    ports:
      - "5173:5173"

volumes:
  mysql_data:

