# Generated by Django 5.2.17 on 2026-10-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraud_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_status',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('FLAGGED', 'Flagged'), ('REVIEWED', 'Reviewed')], db_index=True, default='CLEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
