# Generated by Django 5.2.17 on 2026-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_fraud_reason_transaction_fraud_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
