# Generated by Django 5.2.17 on 2026-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_device_id_transaction_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SHOPPING', 'Shopping'), ('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
